project:
  type: website
  resources:
    - data/


filters:
  - strip-solution

website:
  title: "Protein Science"

  sidebar:
    style: "docked"
    contents:
      - href: index.qmd
        text: Home
        icon: house
      - section: "Exercises"
        contents:
          - content/fitting.qmd

format:
  html:
    theme:
      light: [flatly, styles.scss]
      dark: [darkly, styles.scss]
    css: styles.css
    toc: true
    mainfont: "inter, sans-serif"
    monofont: "JetBrains Mono, monospace"

teaching:
  show-solutions: true
  default-solution-title: "Solution"



